- name: update cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install openvpn and easy-rsa 3
  ansible.builtin.apt:
    name:
      - openvpn
      - easy-rsa

- name: ensure /etc/openvpn/easy-rsa exists
  ansible.builtin.file:
    path: /etc/openvpn/easy-rsa
    state: directory
    mode: "0755"

- name: copy files /usr/share/easy-rsa/easyrsa to /etc/openvpn
  ansible.builtin.copy:
    src: /usr/share/easy-rsa/
    dest: /etc/openvpn/easy-rsa
    mode: "0640"
    remote_src: yes

- name: easyrsa init-pki
  ansible.builtin.command:
    cmd: "/etc/openvpn/easy-rsa/easyrsa init-pki"
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki

- name: easyrsa build-ca
  ansible.builtin.command:
    cmd: /etc/openvpn/easy-rsa/easyrsa build-ca nopass
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki/ca.crt
  environment:
    EASYRSA_BATCH: "yes"

- name: easyrsa gen-dh
  ansible.builtin.command:
    cmd: /etc/openvpn/easy-rsa/easyrsa gen-dh
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki/dh.pem

- name: easyrsa build-server-full server nopass
  ansible.builtin.command:
    cmd: /etc/openvpn/easy-rsa/easyrsa build-server-full server nopass
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki/issued/server.crt

- name: easyrsa build-client-full client nopass
  ansible.builtin.command:
    cmd: /etc/openvpn/easy-rsa/easyrsa build-client-full client nopass
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki/issued/client.crt

- name: easyrsa gen-crl
  ansible.builtin.command:
    cmd: /etc/openvpn/easy-rsa/easyrsa gen-crl
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki/crl.pem

- name: openvpn --genkey --secret /etc/openvpn/easy-rsa/pki/ta.key
  ansible.builtin.command:
    cmd: openvpn --genkey --secret /etc/openvpn/easy-rsa/pki/ta.key
    creates: /etc/openvpn/easy-rsa/pki/ta.key

- name: copy files to /etc/openvpn/server
  ansible.builtin.copy:
    src: /etc/openvpn/easy-rsa/pki/{{ item }}
    dest: /etc/openvpn/server/{{ item | basename }}
    mode: "0640"
    remote_src: yes
  loop:
    - ca.crt
    - dh.pem
    - ta.key
    - issued/client.crt
    - issued/server.crt
    - private/ca.key
    - private/client.key
    - private/server.key

# - name: copy files to /etc/openvpn
#   ansible.builtin.copy:
#     src: /etc/openvpn/easy-rsa/pki/{{ item }}
#     dest: /etc/openvpn/{{ item | basename }}
#     mode: "0640"
#     remote_src: yes
#   loop:
#     - ca.crt
#     - ta.key

- name: place server.conf
  ansible.builtin.template:
    src: server.conf.j2
    dest: "/etc/openvpn/server/server.conf"
    owner: root
    group: root
    mode: "0640"
  notify:
    - restart openvpn

- name: enable openvpn
  ansible.builtin.service:
    name: openvpn-server@server
    enabled: yes

- name: create directory for clients config and cert if it does not exist
  ansible.builtin.file:
    path: /etc/openvpn/for_vpn_clients
    state: directory
    mode: '0755'
